### ISSUE TITLE
pipe not working

### ISSUE THREAD

**Issue by jimlynnjulian** [jwdev42/imdb2mkvtags#1]
"imdb2mkvtags https://www.imdb.com/title/tt0086465 > example1.xml"
Generates the same text as without the pipe, but adds:

[Error] - Movie: Could not set field "Actors": CreditsList: No div container found with attribute data-testid=title-pc-wide-screen
[Error] - Movie: Could not set field "DateReleased": No element found with attribute data-testid="hero-title-block__metadata"
[Error] - Movie: Could not set field "Directors": CreditsList: No div container found with attribute data-testid=title-pc-wide-screen
[Error] - Movie: Could not set field "Titles": No element found with attribute data-testid="hero-title-block__title"
[Error] - Movie: Could not set field "Writers": CreditsList: No div container found with attribute data-testid=title-pc-wide-screen
[Error] - Country: Could not set field "LawRating": No element found with attribute data-testid="hero-title-block__metadata"

**Comment by jimlynnjulian** [comment]
Second example gave an alternate method of sending the text to file.

**Comment by jwdev42** [comment]
It doesn't have anything to do with pipe. IMDB is currently rolling out a new version of their website. When you make a request, sometimes you'll get the old website and sometimes you'll get the new one that doesn't work with the tool yet.
As a temporary workaround you might use "imdb2mkvtags -opts jsonld=1". That will scrape a different dataset that hasn't been changed.

**Comment by jimlynnjulian** [comment]
Thanks for the info. The second example in the package worked fine. However, I'll test your suggestion as an improvement.

**Comment by jimlynnjulian** [comment]
Closing.
